spring.application.name=backend-pedidos360-tnt
server.port=8080

# Configuración de Azure Entra ID
spring.cloud.azure.active-directory.enabled=true
spring.cloud.azure.active-directory.profile.tenant-id=bb5324af-c266-41ed-b36c-a971641c7af2
spring.cloud.azure.active-directory.credential.client-id=979b7949-f63b-4e7c-baa8-e382982acee6
spring.cloud.azure.active-directory.app-id-uri=api://979b7949-f63b-4e7c-baa8-e382982acee6